 import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"],variable:"--inter" });
export const metadata = {
  title: "XWEAR",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      
      <body className={`${ inter.variable}`}>{children} </body>
    </html>
  );
}
